// Generated by scripts/glyphs.mjs from the Roboto faces pdfmake embeds and the Tajawal faces in
// assets/fonts/tajawal: run npm run glyphs, never edit by hand. test/render/glyphs.test.ts fails
// when these tables and the fonts disagree.

/** The code points every embedded Roboto face draws, as inclusive ranges. */
export const RANGES: readonly (readonly [number, number])[] = [
  [0x0020, 0x007e], [0x00a0, 0x017f], [0x018f, 0x018f], [0x0192, 0x0192], [0x01a0, 0x01a1], [0x01af, 0x01b0],
  [0x01f0, 0x01f0], [0x01fa, 0x01ff], [0x0218, 0x021b], [0x0237, 0x0237], [0x0259, 0x0259], [0x02bc, 0x02bc],
  [0x02c6, 0x02c7], [0x02c9, 0x02c9], [0x02d8, 0x02dd], [0x02f3, 0x02f3], [0x0300, 0x0301], [0x0303, 0x0303],
  [0x0309, 0x0309], [0x030f, 0x030f], [0x0323, 0x0323], [0x0384, 0x038a], [0x038c, 0x038c], [0x038e, 0x03a1],
  [0x03a3, 0x03ce], [0x03d1, 0x03d2], [0x03d6, 0x03d6], [0x0400, 0x0486], [0x0488, 0x0513], [0x1e00, 0x1e01],
  [0x1e3e, 0x1e3f], [0x1e80, 0x1e85], [0x1e9e, 0x1e9e], [0x1ea0, 0x1ef9], [0x1f4d, 0x1f4d], [0x2000, 0x200b],
  [0x2010, 0x2011], [0x2013, 0x2015], [0x2017, 0x201e], [0x2020, 0x2022], [0x2025, 0x2027], [0x2030, 0x2030],
  [0x2032, 0x2033], [0x2039, 0x203a], [0x203c, 0x203c], [0x2044, 0x2044], [0x2070, 0x2070], [0x2074, 0x208e],
  [0x20a3, 0x20a4], [0x20a6, 0x20ac], [0x20b1, 0x20b1], [0x20b9, 0x20ba], [0x20bc, 0x20bd], [0x20c1, 0x20c1],
  [0x2105, 0x2105], [0x2113, 0x2113], [0x2116, 0x2116], [0x2122, 0x2122], [0x2126, 0x2126], [0x212e, 0x212e],
  [0x215b, 0x215e], [0x2202, 0x2202], [0x2206, 0x2206], [0x220f, 0x220f], [0x2211, 0x2212], [0x221a, 0x221a],
  [0x221e, 0x221e], [0x222b, 0x222b], [0x2248, 0x2248], [0x2260, 0x2260], [0x2264, 0x2265], [0x25a0, 0x25a0],
  [0x25ca, 0x25cb], [0x25cf, 0x25cf], [0xee01, 0xee02], [0xf6c3, 0xf6c3], [0xfb01, 0xfb04], [0xfeff, 0xfeff],
  [0xfffc, 0xfffd], [0xffff, 0xffff],
];

function covered(point: number): boolean {
  let low = 0;
  let high = RANGES.length - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    const [first, last] = RANGES[middle]!;
    if (point < first) high = middle - 1;
    else if (point > last) low = middle + 1;
    else return true;
  }
  return false;
}

// Arabic text prints in Tajawal (render/fonts/tajawal.ts); a run without Arabic prints in Roboto,
// or in Tajawal on an Arabic page when Tajawal draws it (render/pdf.ts forScript).

/** The Unicode Arabic blocks: what makes a run Arabic, whether or not Tajawal draws every character of it. */
const ARABIC_BLOCKS: readonly (readonly [number, number])[] = [
  [0x0600, 0x06ff], [0x0750, 0x077f], [0x08a0, 0x08ff], [0xfb50, 0xfdff], [0xfe70, 0xfeff],
];

/** The code points both Tajawal faces draw, as inclusive ranges. */
export const TAJAWAL_RANGES: readonly (readonly [number, number])[] = [
  [0x0020, 0x007e], [0x00a0, 0x00ac], [0x00ae, 0x00ff], [0x0131, 0x0131], [0x0141, 0x0142], [0x0152, 0x0153],
  [0x0160, 0x0161], [0x0178, 0x0178], [0x017d, 0x017e], [0x0192, 0x0192], [0x02c6, 0x02c7], [0x02d8, 0x02dd],
  [0x03c0, 0x03c0], [0x060c, 0x060c], [0x061b, 0x061b], [0x061f, 0x061f], [0x0621, 0x063a], [0x0640, 0x0655],
  [0x0660, 0x066a], [0x066d, 0x066e], [0x0670, 0x0670], [0x067e, 0x067e], [0x06a4, 0x06a4], [0x2002, 0x200a],
  [0x2011, 0x2015], [0x2018, 0x201a], [0x201c, 0x201e], [0x2020, 0x2022], [0x2026, 0x2026], [0x2030, 0x2030],
  [0x2039, 0x203a], [0x2044, 0x2044], [0x20ac, 0x20ac], [0x2122, 0x2122], [0x2126, 0x2126], [0x2202, 0x2202],
  [0x2206, 0x2206], [0x220f, 0x220f], [0x2211, 0x2212], [0x221a, 0x221a], [0x221e, 0x221e], [0x222b, 0x222b],
  [0x2248, 0x2248], [0x2260, 0x2260], [0x2264, 0x2265], [0x25cc, 0x25cc], [0xe028, 0xe028], [0xe030, 0xe030],
  [0xe03d, 0xe03e], [0xe800, 0xe800], [0xfb00, 0xfb03], [0xfb57, 0xfb59], [0xfb6b, 0xfb6d], [0xfbb2, 0xfbb7],
  [0xfbe8, 0xfbe9], [0xfc59, 0xfc5a], [0xfc5e, 0xfc63], [0xfc95, 0xfc96], [0xfd3e, 0xfd3f], [0xfdf2, 0xfdf2],
  [0xfe82, 0xfe82], [0xfe84, 0xfe84], [0xfe86, 0xfe86], [0xfe88, 0xfe88], [0xfe8a, 0xfe8c], [0xfe8e, 0xfe8e],
  [0xfe90, 0xfe92], [0xfe94, 0xfe94], [0xfe96, 0xfe98], [0xfe9a, 0xfe9c], [0xfe9e, 0xfea0], [0xfea2, 0xfea4],
  [0xfea6, 0xfea8], [0xfeaa, 0xfeaa], [0xfeac, 0xfeac], [0xfeae, 0xfeae], [0xfeb0, 0xfeb0], [0xfeb2, 0xfeb4],
  [0xfeb6, 0xfeb8], [0xfeba, 0xfebc], [0xfebe, 0xfec0], [0xfec2, 0xfec4], [0xfec6, 0xfec8], [0xfeca, 0xfecc],
  [0xfece, 0xfed0], [0xfed2, 0xfed4], [0xfed6, 0xfed8], [0xfeda, 0xfedc], [0xfede, 0xfee0], [0xfee2, 0xfee4],
  [0xfee6, 0xfee8], [0xfeea, 0xfeec], [0xfeee, 0xfeee], [0xfef0, 0xfef0], [0xfef2, 0xfefc], [0xffff, 0xffff],
];

const within = (point: number, ranges: readonly (readonly [number, number])[]): boolean => {
  let low = 0;
  let high = ranges.length - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    const [first, last] = ranges[middle]!;
    if (point < first) high = middle - 1;
    else if (point > last) low = middle + 1;
    else return true;
  }
  return false;
};

export function isArabic(point: number): boolean {
  return within(point, ARABIC_BLOCKS);
}

/** True when `text` holds at least one Arabic character. */
export function hasArabic(text: string): boolean {
  for (const character of text) if (isArabic(character.codePointAt(0)!)) return true;
  return false;
}

/** True when Tajawal, the face of every Arabic run, draws this code point. */
export function inTajawal(point: number): boolean {
  return within(point, TAJAWAL_RANGES);
}

/** Each Tajawal code point's advance in thousandths of an em, in TAJAWAL_RANGES order: the wider face's; a mark is 0. */
export const TAJAWAL_ADVANCES: readonly number[] = [
  240, 280, 356, 497, 567, 781, 593, 230, 368, 368, 332, 518, 196, 298, 328, 327, 563, 375, 480, 503,
  563, 515, 523, 423, 536, 523, 288, 199, 517, 516, 517, 397, 698, 586, 555, 572, 631, 526, 513, 594,
  692, 289, 269, 596, 468, 837, 718, 654, 540, 654, 525, 536, 542, 648, 569, 872, 609, 573, 484, 349,
  372, 349, 450, 404, 226, 502, 561, 477, 561, 526, 385, 551, 551, 252, 263, 496, 262, 886, 552, 533,
  549, 551, 417, 428, 397, 538, 489, 716, 479, 499, 423, 396, 277, 396, 508, 240, 280, 487, 503, 490,
  530, 230, 468, 373, 699, 268, 658, 477, 414, 256, 278, 516, 367, 371, 226, 600, 543, 186, 213, 325,
  290, 658, 891, 845, 877, 397, 586, 586, 586, 586, 586, 586, 846, 572, 526, 526, 526, 526, 289, 289,
  289, 289, 655, 718, 654, 654, 654, 654, 654, 501, 654, 648, 648, 648, 648, 573, 533, 512, 502, 502,
  502, 502, 502, 502, 795, 481, 526, 526, 526, 526, 281, 273, 281, 281, 522, 549, 538, 538, 538, 538,
  538, 458, 533, 538, 538, 538, 538, 479, 547, 479, 281, 477, 288, 853, 863, 536, 428, 573, 484, 423,
  403, 266, 269, 270, 142, 166, 217, 297, 397, 561, 298, 304, 456, 542, 306, 306, 522, 306, 755, 306,
  898, 541, 898, 898, 631, 651, 651, 477, 477, 360, 360, 1368, 1368, 1348, 1348, 906, 906, 581, 581, 116,
  980, 779, 897, 724, 623, 699, 541, 522, 755, 755, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 340, 266, 415, 614, 440, 461, 415, 539, 539, 456, 781, 364, 898, 0, 898, 980, 521, 1042, 347,
  260, 69, 583, 265, 130, 35, 264, 583, 397, 648, 771, 321, 321, 321, 536, 541, 541, 428, 428, 331,
  563, 1108, 373, 373, 483, 626, 655, 616, 515, 653, 662, 536, 516, 588, 573, 407, 505, 516, 516, 516,
  428, 0, 938, 719, 814, 0, 770, 637, 647, 1022, 938, 346, 386, 999, 563, 575, 0, 0, 0, 0,
  0, 0, 346, 386, 1104, 1104, 0, 0, 0, 0, 0, 0, 1130, 1130, 432, 432, 1450, 346, 346, 535,
  346, 675, 339, 386, 346, 918, 346, 386, 543, 918, 346, 386, 918, 346, 386, 721, 582, 676, 741, 582,
  676, 741, 582, 676, 538, 538, 401, 401, 1425, 1032, 1089, 1425, 1032, 1089, 1413, 995, 1060, 1413, 995, 1060,
  972, 837, 901, 972, 837, 901, 685, 574, 708, 685, 574, 708, 999, 563, 575, 791, 563, 575, 938, 499,
  559, 778, 333, 374, 673, 588, 665, 739, 346, 386, 543, 647, 713, 535, 675, 675, 346, 386, 690, 731,
  690, 731, 690, 731, 690, 731, 240,
];

/** Each Arabic letter's advance in its forms [isolated, final, initial, medial], as Tajawal's shaper sets it. */
export const FORMS: ReadonlyMap<number, readonly number[]> = new Map([
  [0x0621, [542, 542, 542, 542]], [0x0622, [306, 346, 306, 346]], [0x0623, [306, 346, 306, 346]], [0x0624, [522, 535, 522, 535]],
  [0x0625, [306, 346, 306, 346]], [0x0626, [755, 675, 339, 386]], [0x0627, [306, 346, 306, 346]], [0x0628, [898, 918, 346, 386]],
  [0x0629, [541, 543, 541, 543]], [0x062a, [898, 918, 346, 386]], [0x062b, [898, 918, 346, 386]], [0x062c, [631, 721, 582, 676]],
  [0x062d, [651, 741, 582, 676]], [0x062e, [651, 741, 582, 676]], [0x062f, [477, 538, 477, 538]], [0x0630, [477, 538, 477, 538]],
  [0x0631, [360, 401, 360, 401]], [0x0632, [360, 401, 360, 401]], [0x0633, [1368, 1425, 1032, 1089]], [0x0634, [1368, 1425, 1032, 1089]],
  [0x0635, [1348, 1413, 995, 1060]], [0x0636, [1348, 1413, 995, 1060]], [0x0637, [906, 972, 837, 901]], [0x0638, [906, 972, 837, 901]],
  [0x0639, [581, 685, 574, 708]], [0x063a, [581, 685, 574, 708]], [0x0640, [116, 116, 116, 116]], [0x0641, [980, 999, 563, 575]],
  [0x0642, [779, 791, 563, 575]], [0x0643, [897, 938, 499, 559]], [0x0644, [724, 778, 333, 374]], [0x0645, [623, 673, 588, 665]],
  [0x0646, [699, 739, 346, 386]], [0x0647, [541, 543, 647, 713]], [0x0648, [522, 535, 522, 535]], [0x0649, [755, 675, 346, 386]],
  [0x064a, [755, 675, 346, 386]], [0x066e, [898, 938, 898, 898]], [0x067e, [898, 938, 346, 386]], [0x06a4, [980, 999, 563, 575]],
]);

/** The letters that join to the letter after them. */
export const DUAL: ReadonlySet<number> = new Set([
  0x0626, 0x0628, 0x062a, 0x062b, 0x062c, 0x062d, 0x062e, 0x0633, 0x0634, 0x0635, 0x0636, 0x0637,
  0x0638, 0x0639, 0x063a, 0x0641, 0x0642, 0x0643, 0x0644, 0x0645, 0x0646, 0x0647, 0x0649, 0x064a,
  0x067e, 0x06a4,
]);

const TAJAWAL_STARTS: number[] = [];
for (let index = 0, total = 0; index < TAJAWAL_RANGES.length; index++) {
  TAJAWAL_STARTS.push(total);
  total += TAJAWAL_RANGES[index]![1] - TAJAWAL_RANGES[index]![0] + 1;
}

function tajawalAdvance(point: number): number {
  let low = 0;
  let high = TAJAWAL_RANGES.length - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    const [first, last] = TAJAWAL_RANGES[middle]!;
    if (point < first) high = middle - 1;
    else if (point > last) low = middle + 1;
    else return TAJAWAL_ADVANCES[TAJAWAL_STARTS[middle]! + point - first]!;
  }
  return 1000;
}

/** The tatweel stretches a join: it joins on both sides. */
const TATWEEL = 0x0640;

/**
 * A run's width in Tajawal, in thousandths of an em: each letter in the form its neighbours give it,
 * as the shaper picks it. A mark sits on its letter and does not break the join. Ligatures (lam-alef)
 * and kerning are ignored, so the result errs wide.
 */
function tajawalWidth(text: string): number {
  const points = [...text].map((character) => character.codePointAt(0)!);
  const isMark = (point: number): boolean => isArabic(point) && tajawalAdvance(point) === 0;
  const neighbour = (from: number, step: number): number | undefined => {
    for (let at = from + step; at >= 0 && at < points.length; at += step) if (!isMark(points[at]!)) return points[at];
    return undefined;
  };
  const joinsNext = (point: number): boolean => DUAL.has(point) || point === TATWEEL;
  let total = 0;
  points.forEach((point, index) => {
    const forms = FORMS.get(point);
    if (!forms) {
      total += tajawalAdvance(point);
      return;
    }
    const previous = neighbour(index, -1);
    const next = neighbour(index, 1);
    const fromPrevious = previous !== undefined && joinsNext(previous);
    const toNext = DUAL.has(point) && next !== undefined && (FORMS.has(next) || next === TATWEEL);
    total += forms[fromPrevious ? (toNext ? 3 : 1) : toNext ? 2 : 0]!;
  });
  return total;
}

/**
 * The characters of `text` no embedded face can draw, in order; a line break is layout, not a glyph.
 * A run with Arabic in it prints in Tajawal, so every character of it must be one Tajawal draws.
 */
export function undrawable(text: string): string {
  const drawable = hasArabic(text) ? inTajawal : covered;
  let found = '';
  for (const character of text) {
    if (character !== '\n' && !drawable(character.codePointAt(0)!)) found += character;
  }
  return found;
}

/** Each drawable code point's advance in thousandths of an em, in RANGES order: the widest face's. */
export const ADVANCES: readonly number[] = [
  249, 265, 321, 616, 569, 737, 642, 175, 347, 350, 444, 568, 224, 340, 278, 413, 569, 569, 569, 569,
  569, 569, 569, 569, 569, 569, 264, 240, 509, 563, 523, 487, 898, 664, 632, 653, 657, 569, 553, 682,
  714, 284, 556, 632, 541, 875, 714, 689, 639, 689, 630, 606, 610, 655, 646, 888, 632, 611, 604, 272,
  417, 272, 429, 452, 321, 544, 563, 524, 564, 536, 354, 567, 556, 255, 251, 522, 255, 877, 557, 571,
  563, 569, 354, 517, 334, 557, 497, 752, 503, 490, 503, 339, 249, 339, 681, 249, 266, 564, 589, 714,
  532, 247, 622, 447, 786, 448, 486, 554, 340, 787, 482, 383, 537, 370, 370, 323, 595, 490, 284, 260,
  370, 457, 486, 733, 776, 795, 487, 664, 664, 664, 664, 664, 664, 937, 653, 569, 569, 569, 569, 284,
  284, 284, 284, 671, 714, 689, 689, 689, 689, 689, 534, 688, 655, 655, 655, 655, 611, 602, 615, 544,
  544, 544, 544, 544, 544, 845, 524, 536, 536, 536, 536, 262, 262, 262, 262, 587, 557, 571, 571, 571,
  571, 571, 572, 567, 557, 557, 557, 557, 490, 577, 490, 664, 544, 664, 544, 664, 544, 653, 524, 653,
  524, 653, 524, 653, 524, 657, 638, 671, 616, 569, 536, 569, 536, 569, 536, 569, 536, 569, 536, 682,
  567, 682, 567, 682, 567, 682, 567, 714, 556, 711, 571, 284, 262, 284, 262, 284, 262, 284, 255, 284,
  262, 839, 506, 556, 269, 632, 522, 576, 541, 255, 541, 255, 541, 329, 541, 363, 549, 291, 714, 557,
  714, 557, 714, 557, 557, 699, 567, 689, 571, 689, 571, 689, 571, 961, 909, 630, 354, 630, 354, 630,
  354, 606, 517, 606, 517, 606, 517, 606, 517, 610, 334, 610, 353, 610, 334, 655, 557, 655, 557, 655,
  557, 655, 557, 655, 557, 655, 557, 888, 752, 611, 490, 611, 604, 503, 604, 503, 604, 503, 254, 694,
  352, 696, 577, 705, 619, 269, 664, 544, 937, 845, 688, 567, 606, 517, 610, 334, 269, 528, 216, 484,
  459, 482, 437, 255, 335, 288, 476, 395, 307, 0, 0, 0, 0, 0, 0, 303, 529, 664, 284, 618,
  763, 333, 699, 660, 679, 331, 664, 632, 557, 720, 569, 604, 714, 685, 284, 632, 656, 875, 714, 572,
  689, 714, 639, 572, 610, 611, 747, 632, 712, 669, 284, 611, 566, 550, 567, 331, 546, 566, 598, 507,
  567, 550, 519, 567, 582, 331, 576, 555, 595, 497, 513, 571, 624, 567, 539, 570, 522, 546, 728, 555,
  725, 824, 331, 546, 571, 546, 824, 588, 566, 810, 569, 569, 750, 557, 675, 606, 284, 284, 556, 1072,
  1081, 814, 632, 714, 631, 713, 664, 631, 632, 557, 752, 569, 958, 607, 714, 714, 645, 709, 875, 714,
  689, 714, 639, 653, 610, 631, 797, 632, 747, 690, 951, 998, 767, 868, 628, 675, 923, 637, 544, 563,
  572, 420, 619, 536, 816, 512, 578, 578, 553, 579, 751, 577, 571, 578, 563, 524, 498, 490, 729, 503,
  602, 550, 819, 868, 642, 805, 552, 539, 817, 555, 536, 536, 556, 420, 539, 517, 255, 262, 251, 855,
  862, 567, 553, 578, 490, 578, 918, 802, 628, 551, 897, 751, 636, 549, 912, 780, 862, 736, 1146, 992,
  518, 495, 712, 725, 685, 569, 637, 507, 637, 507, 1179, 1058, 685, 567, 917, 792, 918, 802, 650, 536,
  625, 0, 0, 0, 0, 0, 0, 766, 635, 628, 551, 639, 568, 553, 455, 557, 420, 615, 518, 1018,
  860, 607, 512, 724, 623, 648, 584, 655, 534, 823, 704, 766, 629, 983, 713, 1036, 870, 777, 627, 653,
  524, 610, 498, 611, 507, 611, 507, 653, 532, 897, 680, 744, 608, 680, 557, 690, 556, 774, 596, 774,
  596, 284, 958, 816, 641, 559, 766, 635, 713, 567, 771, 634, 690, 550, 933, 807, 284, 664, 544, 664,
  544, 937, 845, 569, 536, 694, 528, 694, 528, 958, 816, 607, 512, 583, 583, 714, 578, 714, 578, 689,
  571, 685, 569, 685, 569, 675, 539, 631, 490, 631, 490, 631, 490, 690, 550, 557, 420, 868, 805, 596,
  459, 677, 556, 632, 503, 622, 564, 869, 862, 793, 647, 564, 536, 970, 831, 998, 830, 628, 523, 710,
  642, 675, 550, 785, 654, 664, 544, 875, 877, 888, 752, 888, 752, 888, 752, 665, 664, 544, 664, 544,
  664, 544, 664, 544, 664, 544, 664, 544, 664, 544, 664, 544, 664, 544, 664, 544, 664, 544, 664, 544,
  569, 536, 569, 536, 569, 536, 569, 536, 569, 536, 569, 536, 569, 536, 569, 536, 284, 262, 284, 255,
  689, 571, 689, 571, 689, 571, 689, 571, 689, 571, 689, 571, 689, 571, 696, 577, 696, 577, 696, 577,
  696, 577, 696, 577, 655, 557, 655, 557, 705, 619, 705, 619, 705, 619, 705, 619, 705, 619, 611, 490,
  611, 490, 611, 490, 611, 490, 724, 510, 1021, 510, 1021, 341, 255, 170, 563, 274, 205, 105, 0, 340,
  340, 657, 781, 781, 457, 219, 216, 226, 205, 381, 385, 375, 552, 576, 350, 499, 709, 227, 960, 175,
  321, 307, 302, 530, 455, 370, 370, 370, 370, 370, 370, 370, 403, 372, 372, 252, 252, 423, 370, 370,
  370, 370, 370, 370, 370, 370, 370, 370, 403, 372, 372, 252, 252, 553, 589, 804, 844, 1073, 779, 826,
  579, 569, 740, 522, 576, 673, 687, 760, 739, 486, 1029, 629, 669, 637, 777, 859, 852, 834, 572, 720,
  695, 609, 572, 597, 1041, 275, 571, 563, 509, 523, 605, 507, 605, 605, 290, 321, 252, 585, 593, 895,
  895, 0, 1026, 1026, 449,
];

/** Where each range's advances start in ADVANCES. */
const STARTS: number[] = [];
for (let index = 0, total = 0; index < RANGES.length; index++) {
  STARTS.push(total);
  total += RANGES[index]![1] - RANGES[index]![0] + 1;
}

function advance(point: number): number {
  let low = 0;
  let high = RANGES.length - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    const [first, last] = RANGES[middle]!;
    if (point < first) high = middle - 1;
    else if (point > last) low = middle + 1;
    else return ADVANCES[STARTS[middle]! + point - first]!;
  }
  return 1000;
}

/**
 * How wide `text` sets at `size` points, ignoring kerning: never narrower than any face draws it.
 * A run with Arabic in it prints in Tajawal (render/pdf.ts), so it is measured in Tajawal.
 */
export function textWidth(text: string, size: number): number {
  if (hasArabic(text)) return (tajawalWidth(text) * size) / 1000;
  let thousandths = 0;
  for (const character of text) thousandths += advance(character.codePointAt(0)!);
  return (thousandths * size) / 1000;
}
