// Writes render/glyphs.ts: the characters every Roboto face pdfmake embeds can
// draw, read from the fonts' own character maps. A hand-written list drifts from
// the font; this one cannot. Run: npm run glyphs
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const FACES = ['Roboto-Regular.ttf', 'Roboto-Medium.ttf', 'Roboto-Italic.ttf', 'Roboto-MediumItalic.ttf'];

function faces() {
  const fontkit = require('fontkit');
  const vfs = require('pdfmake/build/vfs_fonts.js');
  return FACES.map((face) => fontkit.create(Buffer.from(vfs[face], 'base64')));
}

function common(fonts) {
  const sets = fonts.map((font) => new Set(font.characterSet));
  return [...sets[0]].filter((point) => point >= 0x20 && sets.every((set) => set.has(point))).sort((a, b) => a - b);
}

/** Inclusive [first, last] code point ranges that all four faces draw. */
export function robotoRanges() {
  const ranges = [];
  for (const point of common(faces())) {
    const last = ranges.at(-1);
    if (last && point === last[1] + 1) last[1] = point;
    else ranges.push([point, point]);
  }
  return ranges;
}

/** Each drawable code point's advance, in thousandths of an em: the widest of the four faces, rounded up. */
export function robotoAdvances() {
  const fonts = faces();
  return common(fonts).map((point) =>
    Math.max(...fonts.map((font) => Math.ceil((font.glyphForCodePoint(point).advanceWidth * 1000) / font.unitsPerEm))));
}

const hex = (point) => `0x${point.toString(16).padStart(4, '0')}`;

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  const ranges = robotoRanges();
  const advances = robotoAdvances();
  const rows = [];
  for (let index = 0; index < ranges.length; index += 6) {
    rows.push(`  ${ranges.slice(index, index + 6).map(([first, last]) => `[${hex(first)}, ${hex(last)}]`).join(', ')},`);
  }
  const advanceRows = [];
  for (let index = 0; index < advances.length; index += 20) advanceRows.push(`  ${advances.slice(index, index + 20).join(', ')},`);
  const source = `// Generated by scripts/glyphs.mjs from the Roboto faces pdfmake embeds: run
// npm run glyphs, never edit by hand. test/render/glyphs.test.ts fails when this
// list and the fonts disagree.

/** The code points every embedded Roboto face draws, as inclusive ranges. */
export const RANGES: readonly (readonly [number, number])[] = [
${rows.join('\n')}
];

function covered(point: number): boolean {
  let low = 0;
  let high = RANGES.length - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    const [first, last] = RANGES[middle]!;
    if (point < first) high = middle - 1;
    else if (point > last) low = middle + 1;
    else return true;
  }
  return false;
}

/** The characters of \`text\` no embedded face can draw, in order; a line break is layout, not a glyph. */
export function undrawable(text: string): string {
  let found = '';
  for (const character of text) {
    if (character !== '\\n' && !covered(character.codePointAt(0)!)) found += character;
  }
  return found;
}

/** Each drawable code point's advance in thousandths of an em, in RANGES order: the widest face's. */
export const ADVANCES: readonly number[] = [
${advanceRows.join('\n')}
];

/** Where each range's advances start in ADVANCES. */
const STARTS: number[] = [];
for (let index = 0, total = 0; index < RANGES.length; index++) {
  STARTS.push(total);
  total += RANGES[index]![1] - RANGES[index]![0] + 1;
}

function advance(point: number): number {
  let low = 0;
  let high = RANGES.length - 1;
  while (low <= high) {
    const middle = (low + high) >> 1;
    const [first, last] = RANGES[middle]!;
    if (point < first) high = middle - 1;
    else if (point > last) low = middle + 1;
    else return ADVANCES[STARTS[middle]! + point - first]!;
  }
  return 1000;
}

/** How wide \`text\` sets at \`size\` points, ignoring kerning: never narrower than any face draws it. */
export function textWidth(text: string, size: number): number {
  let thousandths = 0;
  for (const character of text) thousandths += advance(character.codePointAt(0)!);
  return (thousandths * size) / 1000;
}
`;
  const target = fileURLToPath(new URL('../render/glyphs.ts', import.meta.url));
  writeFileSync(target, source);
  console.log(`wrote ${target}: ${ranges.length} ranges`);
}
