// Registers a universal identifier for every key the app asks for and the
// registry does not have yet. Never changes or removes an existing entry.
// See src/lib/id.ts.
import { readdirSync, writeFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const registryPath = join(root, 'src', 'ids.ts');

process.env.BILLING_IDS_COLLECT = '1';

function tsFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return tsFiles(path);
    return entry.name.endsWith('.ts') ? [path] : [];
  });
}

for (const path of tsFiles(join(root, 'src'))) {
  if (path !== registryPath) await import(pathToFileURL(path).href);
}

const { requestedKeys } = await import(pathToFileURL(join(root, 'src', 'lib', 'id.ts')).href);
const { IDS } = await import(pathToFileURL(registryPath).href);

const missing = [...requestedKeys].filter((key) => !(key in IDS)).sort();
const unused = Object.keys(IDS).filter((key) => !requestedKeys.has(key)).sort();

if (missing.length > 0) {
  const entries = { ...IDS };
  for (const key of missing) entries[key] = randomUUID();
  const body = Object.keys(entries)
    .sort()
    .map((key) => `  '${key}': '${entries[key]}',`)
    .join('\n');
  writeFileSync(
    registryPath,
    '// Generated by scripts/sync-ids.mjs. Append-only: never edit or delete an entry.\n' +
      'export const IDS: Readonly<Record<string, string>> = {\n' +
      body +
      '\n};\n',
  );
}

console.log(`ids:sync registered ${missing.length} new identifier(s).`);
for (const key of missing) console.log(`  + ${key}`);
if (unused.length > 0) {
  console.log(`${unused.length} registered key(s) are no longer asked for; they stay: ${unused.join(', ')}`);
}
